config/routes.rb
StockAnalysis::Application.routes.draw do

  resources :sign_up_projects

    get "system_console_show/index"

    get "system_console_show/show_policy"

    get "system_console_show/show_users"

    get "system_console_show/show_account"

    resources :user_sessions
    match 'login' => 'user_sessions#new', :as => :login
    match 'logout' => 'user_sessions#destroy', :as => :logout
    match 'user_home/:username' => 'user_homes#show', :as => :user_home
    match 'user_home/:username' => 'user_homes#show', :as => :user_home
    root :to => 'user_sessions#new'

    match ':controller(/:action(/:id))(.:format)'
end

app/models/user_home.rb
# -*- encoding : utf-8 -*-
class UserHome < ActiveRecord::Base
    attr_accessible :layouts
    has_many :layouts,:dependent => :destroy,:inverse_of => :user_home
    belongs_to :user,:inverse_of => :user_home
end

app/controllers/user_homes_controller.rb
# -*- encoding : utf-8 -*-
class UserHomesController < ApplicationController
    before_filter :require_user, :only => [:show,:welcome]
    layout 'user_homes_layout'
    # GET /user_homes
    # GET /user_homes.json
    def index
        @user_home = UserHome.find_by_user_id(current_user.id)
        respond_to do |format|
            format.html # index.html.erb
            format.json { render json: @user_home.to_json(:include => :layout) }
        end
    end

    def welcome
        respond_to do |format|
            format.html # show.html.erb
        end
    end

    def show
        my_name = current_user.username
        @is_i_can_change = true if my_name == params[:username]
        @page_user = User.find_by_username(params[:username])
	    userid = current_user.id unless @page_user
	    userid = @page_user.id if @page_user
        logger.debug userid
        @page_user_home = UserHome.find_by_user_id(userid)
        #logger.debug @page_user_home.to_json(:include => {:layouts =>{:include => :desktop_icons}})
        respond_to do |format|
            format.html
            format.json { render json: @page_user_home.to_json(:include => {:layouts =>{:include => :desktop_icons}}) }
        end
    end

    # GET /user_homes/new
    # GET /user_homes/new.json
    def new
        @user_home = UserHome.new

        respond_to do |format|
            format.html # new.html.erb
            format.json { render json: @user_home }
        end
    end

    # GET /user_homes/1/edit
    def edit
        @user_home = UserHome.find(params[:id])
    end

    # POST /user_homes
    # POST /user_homes.json
    def create
        @user_home = UserHome.new(params[:user_home])

        respond_to do |format|
            if @user_home.save
                format.html { redirect_to @user_home, notice: 'User home was successfully created.' }
                format.json { render json: @user_home, status: :created, location: @user_home }
            else
                format.html { render action: "new" }
                format.json { render json: @user_home.errors, status: :unprocessable_entity }
            end
        end
    end

    # PUT /user_homes/1
    # PUT /user_homes/1.json
    def update
        @user_home = UserHome.find(params[:id])

        respond_to do |format|
            if @user_home.update_attributes(params[:user_home])
                format.html { redirect_to @user_home, notice: 'User home was successfully updated.' }
                format.json { head :no_content }
            else
                format.html { render action: "edit" }
                format.json { render json: @user_home.errors, status: :unprocessable_entity }
            end
        end
    end

    # DELETE /user_homes/1
    # DELETE /user_homes/1.json
    def destroy
        @user_home = UserHome.find(params[:id])
        @user_home.destroy

        respond_to do |format|
            format.html { redirect_to user_homes_url }
            format.json { head :no_content }
        end
    end
end

app/helpers/user_homes_helper.rb
# -*- encoding : utf-8 -*-
module UserHomesHelper
end

app/views/user_homes/edit.html.erb
<h1>Editing user_home</h1>

<%= render 'form' %>

<%= link_to 'Show', @user_home %> |
<%= link_to 'Back', user_homes_path %>

app/views/user_homes/index.html.erb
<script type="text/javascript">
    $(function () {
        myLib.progressBar();
    });
    $.include(['assets/user_home/desktop.css', 'assets/user_home/jquery-ui-1.8.18.custom.css', 'assets/user_home/smartMenu.css' , 'assets/user_home/jquery-ui-1.8.18.custom.min.js', 'assets/user_home/jquery.winResize.js', 'assets/user_home/jquery-smartMenu-min.js', 'assets/user_home/desktop.js']);
    $(window).load(function () {
        myLib.stopProgress();
        var lrBarIconData = {
            'app0': {
                'title': 'jsfoot网页特效',
                'url': 'http://www.jsfoot.com/',
                'winWidth': 1100,
                'winHeight': 650
            },
            'app1': {
                'title': 'jQuery特效',
                'url': 'http://www.jsfoot.com/jquery/',
                'winWidth': 1100,
                'winHeight': 650
            },
            'app2': {
                'title': 'javascript特效',
                'url': 'http://www.jsfoot.com/js/',
                'winWidth': 1100,
                'winHeight': 650
            },
            'app3': {
                'title': '资源分享',
                'url': 'ziyuan.html',
                'winWidth': 1100,
                'winHeight': 650
            }
        };
        var deskIconData = {
            'kuwoMusic': {
                'title': '酷我音乐盒',
                'url': 'http://mbox.kuwo.cn/',
                'winWidth': 950,
                'winHeight': 500
            },
            'hudong': {
                'title': '互动百科',
                'url': 'http://lab.hudong.com/webqq/index.html',
                'winWidth': 950,
                'winHeight': 500
            },
            'dubianFim': {
                'title': '豆瓣FIM',
                'url': 'http://douban.fm/partner/qq_plus',
                'winWidth': 550,
                'winHeight': 480
            },
            'Pixlr': {
                'title': 'Pixlr',
                'url': 'http://pixlr.com/editor/?loc=zh-cn',
                'winWidth': 942,
                'winHeight': 547
            },
            'qidian': {
                'title': '起点中文',
                'url': 'http://webqq.qidian.com',
                'winWidth': 942,
                'winHeight': 547
            },
            'leshiwang': {
                'title': '乐视网',
                'url': 'http://www.letv.com/cooperation/qq.html',
                'winWidth': 842,
                'winHeight': 547
            },
            'qianqianMusic': {
                'title': '千千音乐',
                'url': 'http://www.qianqian.com/paihang.html',
                'winWidth': 930,
                'winHeight': 500
            },
            'zfMeishi': {
                'title': '主妇美食',
                'url': 'http://www.zhms.cn/',
                'winWidth': 930,
                'winHeight': 500
            },
            'mglvyou': {
                'title': '芒果旅游',
                'url': 'http://www.mangocity.com/webqq/bookFlight.html',
                'winWidth': 930,
                'winHeight': 500
            },
            'taobao': {
                'title': '淘宝网',
                'url': 'http://marketing.taobao.com/home/webqq/index.htm',
                'winWidth': 930,
                'winHeight': 500
            },
            'qingshu': {
                'title': '情书',
                'url': 'http://www.qingshu8.net/',
                'winWidth': 930,
                'winHeight': 500
            },
            'fenghuang': {
                'title': '凤凰网',
                'url': 'http://www.ifeng.com/',
                'winWidth': 930,
                'winHeight': 500
            },
            'zhongguancun': {
                'title': '中关村在线',
                'url': 'http://www.zol.com.cn/',
                'winWidth': 930,
                'winHeight': 500
            },
            'win35': {
                'title': '搜狐汽车',
                'url': 'http://auto.sohu.com/',
                'winWidth': 930,
                'winHeight': 500
            },
            'win36': {
                'title': '布丁电影票',
                'url': 'http://piao.buding.cn/',
                'winWidth': 900,
                'winHeight': 500
            },
            'win37': {
                'title': '中国数学资源网',
                'url': 'http://www.mathrs.net/',
                'winWidth': 930,
                'winHeight': 500
            },
            'win38': {
                'title': '火影忍者漫画动画',
                'url': 'http://www.manmankan.com/',
                'winWidth': 930,
                'winHeight': 500
            },
            'win39': {
                'title': '潇湘书院',
                'url': 'http://www.xxsy.net/',
                'winWidth': 930,
                'winHeight': 500
            }
        };
        $.ajax({
            url: window.location,
            dataType: 'jsonp',
            data: '',
            jsonp: 'callback',
            success: function (result) {
                alert(result);
                deskIconData_tmp = result.desktop_icons;
                deskIconData = {};
                alert(deskIconData_tmp)
                deskIconData[deskIconData_tmp.icon_id] = {
                    'title' : deskIconData_tmp.title,
                    'url' : deskIconData_tmp.url,
                    'winWidth' : deskIconData_tmp.winWidth,
                    'winHeight' : deskIconData_tmp.winHeight
                };
            },
            timeout: 3000
        });


        //存储桌面布局元素的jquery对象
        myLib.desktop.desktopPanel();

        //初始化桌面背景
        myLib.desktop.wallpaper.init("/assets/login-bg.jpg");

        //初始化任务栏
        myLib.desktop.taskBar.init();

        //初始化桌面图标
        myLib.desktop.deskIcon.init(deskIconData);

        //初始化桌面导航栏
        myLib.desktop.navBar.init();

        //初始化侧边栏
        myLib.desktop.lrBar.init(lrBarIconData);

        //欢迎窗口
        myLib.desktop.win.newWin({
            WindowTitle: '欢迎窗口',
            iframSrc: "/user_homes/welcome",
            WindowsId: "welcome",
            WindowAnimation: 'none',
            WindowWidth: 740,
            WindowHeight: 520
        });

    });
</script>
<body>

<a href="http://www.jsfoot.com/" class="powered_by">Powered by jsfoot.com</a>

<div id="wallpapers"></div>

<div id="navBar"><a href="#" class="currTab" title="桌面1"></a><a href="#" title="桌面2"></a><a href="#" title="桌面3"></a><a
href="#" title="桌面4"></a></div>

<div id="desktopPanel">
  <div id="desktopInnerPanel">
    <ul class="deskIcon currDesktop">
      <li class="desktop_icon" id="leshiwang"><span class="icon"><img src="/assets/user_home/icon/icon4.png"/></span>

        <div class="text">乐视网<s></s></div>
      </li>
      <li class="desktop_icon" id="Pixlr"><span class="icon"><img src="/assets/user_home/icon/icon6.png"/></span>

        <div class="text">Pixlr<s></s></div>
      </li>
      <li class="desktop_icon" id="dubianFim"><span class="icon"><img src="/assets/user_home/icon/icon7.png"/></span>

        <div class="text">豆瓣FIM<s></s></div>
      </li>
      <li class="desktop_icon" id="kuwoMusic"><span class="icon"><img src="/assets/user_home/icon/icon8.png"/></span>

        <div class="text">酷我音乐盒<s></s></div>
      </li>
      <li class="desktop_icon" id="qidian"><span class="icon"><img src="/assets/user_home/icon/icon9.png"/></span>

        <div class="text">起点中文<s></s></div>
      </li>
      <li class="desktop_icon" id="hudong"><span class="icon"><img src="/assets/user_home/icon/icon10.png"/></span>

        <div class="text">互动百科<s></s></div>
      </li>
      <li class="desktop_icon" id="qianqianMusic"><span class="icon"><img src="/assets/user_home/icon/icon5.png"/></span>

        <div class="text">千千音乐<s></s></div>
      </li>
      <li class="desktop_icon add_icon"><span class="icon"><img src="/assets/user_home/images/add_icon.png"/></span>

        <div class="text">添加<s></s></div>
      </li>
    </ul>
    <ul class="deskIcon">
      <li class="desktop_icon" id="zfMeishi"><span class="icon"><img src="/assets/user_home/icon/icon13.png"/></span>

        <div class="text">主妇美食<s></s></div>
      </li>
      <li class="desktop_icon" id="mglvyou"><span class="icon"><img src="/assets/user_home/icon/icon12.png"/></span>

        <div class="text">芒果旅游<s></s></div>
      </li>
      <li class="desktop_icon" id="taobao"><span class="icon"><img src="/assets/user_home/icon/icon14.png"/></span>

        <div class="text">淘宝网<s></s></div>
      </li>
      <li class="desktop_icon" id="qingshu"><span class="icon"><img src="/assets/user_home/icon/icon15.png"/></span>

        <div class="text">情书<s></s></div>
      </li>
      <li class="desktop_icon" id="fenghuang"><span class="icon"><img src="/assets/user_home/icon/icon16.png"/></span>

        <div class="text">凤凰网<s></s></div>
      </li>
      <li class="desktop_icon" id="zhongguancun"><span class="icon"><img src="/assets/user_home/icon/icon17.png"/></span>

        <div class="text">中关村在线<s></s></div>
      </li>
      <li class="desktop_icon add_icon"><span class="icon"><img src="/assets/user_home/images/add_icon.png"/></span>

        <div class="text">添加<s></s></div>
      </li>
    </ul>
    <ul class="deskIcon">
      <li class="desktop_icon" id="win35"><span class="icon"><img src="/assets/user_home/icon/icon18.png"/></span>

        <div class="text">搜狐汽车<s></s></div>
      </li>
      <li class="desktop_icon" id="win36"><span class="icon"><img src="/assets/user_home/icon/icon19.png"/></span>

        <div class="text">布丁电影票<s></s></div>
      </li>
      <li class="desktop_icon" id="win37"><span class="icon"><img src="/assets/user_home/icon/icon8.png"/></span>

        <div class="text">中国数学资源网<s></s></div>
      </li>
      <li class="desktop_icon add_icon"><span class="icon"><img src="/assets/user_home/images/add_icon.png"/></span>

        <div class="text">添加<s></s></div>
      </li>
    </ul>
    <ul class="deskIcon">
      <li class="desktop_icon" id="win38"><span class="icon"><img src="/assets/user_home/icon/icon20.png"/></span>

        <div class="text">火影忍者漫画动画<s></s></div>
      </li>
      <li class="desktop_icon" id="win39"><span class="icon"><img src="/assets/user_home/icon/icon21.png"/></span>

        <div class="text">潇湘书院<s></s></div>
      </li>
      <li class="desktop_icon add_icon"><span class="icon"><img src="/assets/user_home/images/add_icon.png"/></span>

        <div class="text">添加<s></s></div>
      </li>
    </ul>
  </div>
</div>
<!--desktopPanel end-->

<div id="taskBarWrap">
  <div id="taskBar">
    <div id="leftBtn"><a href="#" class="upBtn"></a></div>
    <div id="rightBtn"><a href="#" class="downBtn"></a></div>
    <div id="task_lb_wrap">
      <div id="task_lb"></div>
    </div>
  </div>
</div>
<!--taskBarWrap end-->

<div id="lr_bar">
  <ul id="default_app">
    <li id="app0"><span><img src="/assets/user_home/icon/icon1.png" title="我的博客"/></span>

      <div class="text">我的博客<s></s></div>
    </li>
    <li id="app1"><span><img src="/assets/user_home/icon/icon2.png" title="关于我"/></span>

      <div class="text">关于我<s></s></div>
    </li>
    <li id="app2"><span><img src="/assets/user_home/icon/icon3.png" title="作品"/></span>

      <div class="text">作品<s></s></div>
    </li>
    <li id="app3"><span><img src="/assets/user_home/icon/icon11.png" title="资源分享"/></span>

      <div class="text">资源分享<s></s></div>
    </li>
  </ul>

  <div id="default_tools"><span id="showZm_btn" title="全屏"></span><span id="shizhong_btn" title="时钟"></span><span
  id="weather_btn" title="天气"></span><span id="them_btn" title="主题"></span></div>

  <div id="start_block">
    <a title="开始" id="start_btn"></a>

    <div id="start_item">
      <ul class="item admin">
        <li><span class="adminImg"></span> jsfoot</li>
      </ul>
      <ul class="item">
        <li><span class="sitting_btn"></span>系统设置</li>
        <li><span class="help_btn"></span>使用指南 <b></b></li>
        <li><span class="about_btn"></span>关于我们</li>
        <li><span class="logout_btn"></span>退出系统</li>
      </ul>
    </div>
  </div>

</div>
<!--lr_bar end-->


</body>

app/views/user_homes/new.html.erb
<h1>New user_home</h1>

<%= form_for @user_home, :url => { :action => 'create' }, :builder => LabellingFormBuilder do |f| %>
    <%= f.text_field :first_name %>
    <%= f.text_field :last_name %>
    <%= f.text_area :biography %>
    <%= f.check_box :admin %>
    <%= f.submit %>
<% end %>

<%= link_to 'Back', :controller => 'user_homes', :action => :show %>

app/views/user_homes/welcome.html.erb
<p id="notice"><%= notice %></p>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title>无标题文档</title>
  <style type="text/css">
      <!--
      body,td,th {
          font-size: 14px;
          color: #333;
      }
      body {
          background-color: #FFF;
      }
      *{
          margin:0;
          padding:0;
      }
      p{
          padding:10px;
      }
      -->
  </style></head>

<body>
<p>------------------------------------------------------------------------------------------</p>
<p>更新日志：2012-6-3</p>
<p>1.重新实现窗口最小化的方法</p>
<p>------------------------------------------------------------------------------------------</p>
<p>更新日志：2012-6-2</p>
<p>1.修改窗口随桌面一起切换移动</p>
<p>2.添加全屏功能</p>
<p>3.在ie7+，谷歌，火狐，Safari，Opera下测试通过，ie6仅是png背景透明问题</p>
<p>所以建议使用非ie浏览器浏览</p>
<p>----------------------------------------------------------------------------------------</p>
<p>非常感谢您的关注，此源码暂不对外开放，在此非常抱歉。</p>
<p>如果您需要此源码用于商业项目，请联系我。</p>
<p>如果您仅是学习之用，也可联系我交流技术问题，我将全力提供帮助。</p>
<p>自从发布受到很多网友关注，此代码现在还存在很多问题，且没有详细的接口文档，此代码原本仅是练习作品，最近打算重新编写，如果你有好的建议可以联系我。</p>
<p>-----------------------------------------------------------------------------------------</p>
<p>联系方式：</p>
<p>email:530624206@qq.com</p>
</body>
</html>