config/routes.rb
StockAnalysis::Application.routes.draw do

  resources :sign_up_projects

    get "system_console_show/index"

    get "system_console_show/show_policy"

    get "system_console_show/show_users"

    get "system_console_show/show_account"

    resources :user_sessions
    match 'login' => 'user_sessions#new', :as => :login
    match 'logout' => 'user_sessions#destroy', :as => :logout
    match 'user_home/:username' => 'user_homes#show', :as => :user_home
    match 'user_home/:username' => 'user_homes#show', :as => :user_home
    root :to => 'user_sessions#new'

    match ':controller(/:action(/:id))(.:format)'
end

app/models/sign_up_project.rb
class SignUpProject < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/controllers/sign_up_projects_controller.rb
class SignUpProjectsController < ApplicationController
  # GET /sign_up_projects
  # GET /sign_up_projects.json
  def index
    @sign_up_projects = SignUpProject.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @sign_up_projects }
    end
  end

  # GET /sign_up_projects/1
  # GET /sign_up_projects/1.json
  def show
    @sign_up_project = SignUpProject.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @sign_up_project }
    end
  end

  # GET /sign_up_projects/new
  # GET /sign_up_projects/new.json
  def new
    @sign_up_project = SignUpProject.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @sign_up_project }
    end
  end

  # GET /sign_up_projects/1/edit
  def edit
    @sign_up_project = SignUpProject.find(params[:id])
  end

  # POST /sign_up_projects
  # POST /sign_up_projects.json
  def create
    @sign_up_project = SignUpProject.new(params[:sign_up_project])

    respond_to do |format|
      if @sign_up_project.save
        format.html { redirect_to @sign_up_project, notice: 'Sign up project was successfully created.' }
        format.json { render json: @sign_up_project, status: :created, location: @sign_up_project }
      else
        format.html { render action: "new" }
        format.json { render json: @sign_up_project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /sign_up_projects/1
  # PUT /sign_up_projects/1.json
  def update
    @sign_up_project = SignUpProject.find(params[:id])

    respond_to do |format|
      if @sign_up_project.update_attributes(params[:sign_up_project])
        format.html { redirect_to @sign_up_project, notice: 'Sign up project was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @sign_up_project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sign_up_projects/1
  # DELETE /sign_up_projects/1.json
  def destroy
    @sign_up_project = SignUpProject.find(params[:id])
    @sign_up_project.destroy

    respond_to do |format|
      format.html { redirect_to sign_up_projects_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/sign_up_projects_helper.rb
module SignUpProjectsHelper
end

app/views/sign_up_projects/_form.html.erb
<%= form_for(@sign_up_project) do |f| %>
  <% if @sign_up_project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sign_up_project.errors.count, "error") %> prohibited this sign_up_project from being saved:</h2>

      <ul>
      <% @sign_up_project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sign_up_projects/edit.html.erb
<h1>Editing sign_up_project</h1>

<%= render 'form' %>

<%= link_to 'Show', @sign_up_project %> |
<%= link_to 'Back', sign_up_projects_path %>

app/views/sign_up_projects/index.html.erb
<h1>Listing sign_up_projects</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @sign_up_projects.each do |sign_up_project| %>
  <tr>
    <td><%= link_to 'Show', sign_up_project %></td>
    <td><%= link_to 'Edit', edit_sign_up_project_path(sign_up_project) %></td>
    <td><%= link_to 'Destroy', sign_up_project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Sign up project', new_sign_up_project_path %>

app/views/sign_up_projects/new.html.erb
<h1>New sign_up_project</h1>

<%= render 'form' %>

<%= link_to 'Back', sign_up_projects_path %>

app/views/sign_up_projects/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_sign_up_project_path(@sign_up_project) %> |
<%= link_to 'Back', sign_up_projects_path %>