config/routes.rb
StockAnalysis::Application.routes.draw do

  resources :sign_up_projects

    get "system_console_show/index"

    get "system_console_show/show_policy"

    get "system_console_show/show_users"

    get "system_console_show/show_account"

    resources :user_sessions
    match 'login' => 'user_sessions#new', :as => :login
    match 'logout' => 'user_sessions#destroy', :as => :logout
    match 'user_home/:username' => 'user_homes#show', :as => :user_home
    match 'user_home/:username' => 'user_homes#show', :as => :user_home
    root :to => 'user_sessions#new'

    match ':controller(/:action(/:id))(.:format)'
end

app/models/user.rb
# -*- encoding : utf-8 -*-
class User < ActiveRecord::Base
    attr_accessible :description, :email, :encrypted_passwd, :group_id, :group_name, :phone, :qq, :username,:user_home
    has_one :user_home, :dependent => :destroy,:inverse_of => :user
    has_many :accounts
    acts_as_authentic

    def valid_password?(passwd)
        Digest::MD5.hexdigest(passwd) == self.encrypted_passwd
    end
end

app/controllers/users_controller.rb
# -*- encoding : utf-8 -*-
class UsersController < ApplicationController
    before_filter :require_user, :only => [:show, :edit, :update]

    layout 'extjs'

    def new
        @user = User.new
    end

    def create
        @user = User.find_by_username(params[:user][:username])
        if @user
            render_fail_msg 'Account already registered!'
        elsif params[:user][:password] != params[:user][:password_confirmation]
            render_fail_msg '密码不一致'
        else
            params[:user][:encrypted_passwd] = Digest::MD5.hexdigest(params[:user][:password])
            params[:user].delete :password
            params[:user].delete :password_confirmation
            @user = User.new(params[:user])
            debug "#{@user.username},#{@user.encrypted_passwd}"
            begin
                @user.save!
                @current_user = @user
                render_success_msg 'SuccessFully registered!!'
            rescue => e
                render_fail_msg e.message
            end
        end
    end

    def show
        @user = @current_user
    end

    def edit
        @user = @current_user
    end

    def update
        @user = @current_user # makes our views "cleaner" and more consistent
        params[:user][:encrypted_passwd] = Digest::MD5.hexdigest(params[:user][:password])
        params[:user].delete :password
        params[:user].delete :password_confirmation
        if @user.update_attributes(params[:user])
            flash[:notice] = "Account updated!"
            redirect_to account_url
        else
            render :action => :edit
        end
    end
end

app/helpers/users_helper.rb
# -*- encoding : utf-8 -*-
module UsersHelper
end

app/views/users/_form.html.erb
<%= f.label :username %>

<%= f.text_field :username %>

<%= f.label :email %>

<%= f.text_field :email %>

<%= f.label :password, f.object.new_record? ? nil : "Change password" %>

<%= f.password_field :password %>

<%= f.label :password_confirmation %>

<%= f.password_field :password_confirmation %>

app/views/users/edit.html.erb
Edit My Account
<% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> 条错误信息:</h2>
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
<% end %>
<%= form_for @user, :url => account_path do |f| %>

    <%= render :partial => "form", locals: { f: f } %>

    <%= f.submit "Update" %>

<% end %>

<%= link_to "My Profile", account_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Username</th>
    <th>Encrypted passwd</th>
    <th>Email</th>
    <th>Phone</th>
    <th>Qq</th>
    <th>Description</th>
    <th>Group name</th>
    <th>Group</th>
    <th>Last login</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

  <% @users.each do |user| %>
      <tr>
        <td><%= user.username %></td>
        <td><%= user.encrypted_passwd %></td>
        <td><%= user.email %></td>
        <td><%= user.phone %></td>
        <td><%= user.qq %></td>
        <td><%= user.description %></td>
        <td><%= user.group_name %></td>
        <td><%= user.group_id %></td>
        <td><%= user.last_login %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
  <% end %>
</table>

<br/>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> 条错误信息:</h2>
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
<% end %>
<%= javascript_include_tag 'users' %>

<!--<%= form_for @user, :url => users_path do |f| %>-->

    <!--<%= render :partial => "form", locals: { f: f } %>-->

    <!--<%= f.submit "注册" %>-->

<!--<% end %>-->

app/views/users/show.html.erb
Username: <%= h @user.username %> <br>

Login count: <%= h @user.login_count %> <br>

Last request at: <%= h @user.last_request_at %> <br>

Last login at: <%= h @user.last_login_at %> <br>

Current login at: <%= h @user.current_login_at %> <br>

Last login ip: <%= h @user.last_login_ip %> <br>

Current login ip: <%= h @user.current_login_ip %> <br>

<%= link_to 'Edit', edit_account_path %> |

<%= link_to 'Logout', :logout %>